=== albacg5/big_data/MetadataManagementSystem/OntoMatchMerge/ItemsXSD.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:salus="http://www.salusproject.eu/ontology/item" targetNamespace="http://www.salusproject.eu/ontology/item">
  <xs:element name="Items">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Item" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="ID"/>
              <xs:element type="xs:string" name="Name"/>
              <xs:element type="xs:int" name="ValueCost"/>
              <xs:element type="xs:float" name="Percentage"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== albacg5/big_data/data_management/MetadataManagementSystem/OntoMatchMerge/ItemsXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<salus:Items xmlns:salus="http://www.salusproject.eu/ontology/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.salusproject.eu/ontology/item ItemsXSD.xsd">
  <salus:Item>
    <salus:ID>1</salus:ID>
    <salus:Name>diam</salus:Name>
    <salus:ValueCost>58486</salus:ValueCost>
    <salus:Percentage>0.48</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>2</salus:ID>
    <salus:Name>luctus et</salus:Name>
    <salus:ValueCost>47006</salus:ValueCost>
    <salus:Percentage>0.1</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>3</salus:ID>
    <salus:Name>vel augue</salus:Name>
    <salus:ValueCost>10109</salus:ValueCost>
    <salus:Percentage>0.98</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>4</salus:ID>
    <salus:Name>mi pede malesuada</salus:Name>
    <salus:ValueCost>51011</salus:ValueCost>
    <salus:Percentage>0.55</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>5</salus:ID>
    <salus:Name>justo etiam pretium</salus:Name>
    <salus:ValueCost>73518</salus:ValueCost>
    <salus:Percentage>0.33</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>6</salus:ID>
    <salus:Name>in imperdiet et</salus:Name>
    <salus:ValueCost>36845</salus:ValueCost>
    <salus:Percentage>0.88</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>7</salus:ID>
    <salus:Name>at lorem integer</salus:Name>
    <salus:ValueCost>91721</salus:ValueCost>
    <salus:Percentage>0.33</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>8</salus:ID>
    <salus:Name>vivamus metus arcu</salus:Name>
    <salus:ValueCost>55805</salus:ValueCost>
    <salus:Percentage>0.38</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>9</salus:ID>
    <salus:Name>eleifend quam a</salus:Name>
    <salus:ValueCost>43722</salus:ValueCost>
    <salus:Percentage>0.13</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>10</salus:ID>
    <salus:Name>sociis natoque penatibus</salus:Name>
    <salus:ValueCost>54914</salus:ValueCost>
    <salus:Percentage>0.34</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>11</salus:ID>
    <salus:Name>ultrices erat</salus:Name>
    <salus:ValueCost>56784</salus:ValueCost>
    <salus:Percentage>0.71</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>12</salus:ID>
    <salus:Name>diam vitae quam</salus:Name>
    <salus:ValueCost>19414</salus:ValueCost>
    <salus:Percentage>0.12</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>13</salus:ID>
    <salus:Name>massa</salus:Name>
    <salus:ValueCost>30706</salus:ValueCost>
    <salus:Percentage>0.08</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>14</salus:ID>
    <salus:Name>nisl</salus:Name>
    <salus:ValueCost>65795</salus:ValueCost>
    <salus:Percentage>0.18</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>15</salus:ID>
    <salus:Name>condimentum</salus:Name>
    <salus:ValueCost>92866</salus:ValueCost>
    <salus:Percentage>0.55</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>16</salus:ID>
    <salus:Name>ac lobortis vel</salus:Name>
    <salus:ValueCost>58626</salus:ValueCost>
    <salus:Percentage>0.32</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>17</salus:ID>
    <salus:Name>integer pede</salus:Name>
    <salus:ValueCost>68466</salus:ValueCost>
    <salus:Percentage>0.73</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>18</salus:ID>
    <salus:Name>aliquet at feugiat</salus:Name>
    <salus:ValueCost>88676</salus:ValueCost>
    <salus:Percentage>0.17</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>19</salus:ID>
    <salus:Name>odio</salus:Name>
    <salus:ValueCost>23950</salus:ValueCost>
    <salus:Percentage>0.27</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>20</salus:ID>
    <salus:Name>turpis sed ante</salus:Name>
    <salus:ValueCost>83244</salus:ValueCost>
    <salus:Percentage>0.26</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>21</salus:ID>
    <salus:Name>nullam porttitor</salus:Name>
    <salus:ValueCost>92159</salus:ValueCost>
    <salus:Percentage>0.37</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>22</salus:ID>
    <salus:Name>sed</salus:Name>
    <salus:ValueCost>75514</salus:ValueCost>
    <salus:Percentage>0.89</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>23</salus:ID>
    <salus:Name>justo</salus:Name>
    <salus:ValueCost>83618</salus:ValueCost>
    <salus:Percentage>0.17</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>24</salus:ID>
    <salus:Name>ac neque duis</salus:Name>
    <salus:ValueCost>29392</salus:ValueCost>
    <salus:Percentage>0.04</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>25</salus:ID>
    <salus:Name>nec</salus:Name>
    <salus:ValueCost>68071</salus:ValueCost>
    <salus:Percentage>0.88</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>26</salus:ID>
    <salus:Name>duis aliquam</salus:Name>
    <salus:ValueCost>78150</salus:ValueCost>
    <salus:Percentage>0.27</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>27</salus:ID>
    <salus:Name>semper interdum</salus:Name>
    <salus:ValueCost>86626</salus:ValueCost>
    <salus:Percentage>0.81</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>28</salus:ID>
    <salus:Name>nulla suscipit</salus:Name>
    <salus:ValueCost>97734</salus:ValueCost>
    <salus:Percentage>0.42</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>29</salus:ID>
    <salus:Name>curabitur at</salus:Name>
    <salus:ValueCost>94361</salus:ValueCost>
    <salus:Percentage>0.56</salus:Percentage>
  </salus:Item>
  <salus:Item>
    <salus:ID>30</salus:ID>
    <salus:Name>lobortis ligula sit</salus:Name>
    <salus:ValueCost>18229</salus:ValueCost>
    <salus:Percentage>0.64</salus:Percentage>
  </salus:Item>
</salus:Items>
