<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE OntologyMappings [<!ELEMENT OntologyMappings (Connections?, OntologyMapping+)>
<!ELEMENT Connections (Connection*)>
<!ELEMENT Connection (name, server, type, access+, database, port, username, password)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT server (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT access (#PCDATA)>
<!ELEMENT database (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT OntologyMapping (Ontology,RefOntology?,Mapping)>
<!ELEMENT SQLOperator (#PCDATA)>
<!ELEMENT Ontology (#PCDATA)>
<!ELEMENT RefOntology (#PCDATA)>
<!ELEMENT Mapping (((Mapping,SQLOperator)*,Mapping)|(Tablename,Projections,Selections?))>
<!ELEMENT Tablename (#PCDATA)>
<!ELEMENT Projections (Attribute+)>
<!ELEMENT Attribute (#PCDATA)>
<!ELEMENT Selections (Selection+)>
<!ELEMENT Selection (Column,Operator,Constant)>
<!ELEMENT Column (#PCDATA)>
<!ELEMENT Operator (#PCDATA)>
<!ELEMENT Constant (#PCDATA)>
<!ATTLIST Mapping connectionName CDATA #IMPLIED>
<!ATTLIST Mapping sourceKind CDATA #IMPLIED>
<!ATTLIST Ontology type (concept|property) #REQUIRED>
<!ATTLIST RefOntology type (concept|property) #REQUIRED>
]>

<OntologyMappings>
    <Connections/>
    <OntologyMapping>
        <Ontology type="concept">http://www.salusproject.eu/ontology/test#customer</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename/>
            <Projections>
                <Attribute>/salus:customer</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#C_DOB</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer</Tablename>
            <Projections>
                <Attribute>/@C_DOB</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#C_GNDR</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer</Tablename>
            <Projections>
                <Attribute>/@C_GNDR</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#C_ID</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer</Tablename>
            <Projections>
                <Attribute>/@C_ID</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#C_TAX_ID</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer</Tablename>
            <Projections>
                <Attribute>/@C_TAX_ID</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#C_TIER</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer</Tablename>
            <Projections>
                <Attribute>/@C_TIER</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#elem1</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer</Tablename>
            <Projections>
                <Attribute>/salus:elem1</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#elem2</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer</Tablename>
            <Projections>
                <Attribute>/salus:elem2</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#C_ALT_EMAIL</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer</Tablename>
            <Projections>
                <Attribute>/salus:C_ALT_EMAIL</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#C_PRIM_EMAIL</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer</Tablename>
            <Projections>
                <Attribute>/salus:C_PRIM_EMAIL</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#elem5</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer</Tablename>
            <Projections>
                <Attribute>/salus:elem5</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.salusproject.eu/ontology/test#complextype1</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer</Tablename>
            <Projections>
                <Attribute>/salus:Address/node()</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#hasAddress</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer</Tablename>
            <Projections>
                <Attribute>/salus:Address</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#ctattr1</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer/salus:Address</Tablename>
            <Projections>
                <Attribute>/@ctattr1</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#ctattr2</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer/salus:Address</Tablename>
            <Projections>
                <Attribute>/@ctattr2</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#ctelem1</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer/salus:Address</Tablename>
            <Projections>
                <Attribute>/salus:ctelem1</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#ctelem2</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer/salus:Address</Tablename>
            <Projections>
                <Attribute>/salus:ctelem2</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#ctelem3</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer/salus:Address</Tablename>
            <Projections>
                <Attribute>/salus:ctelem3</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.salusproject.eu/ontology/test#complextype2</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer/salus:Address</Tablename>
            <Projections>
                <Attribute>/salus:ctelem4/node()</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#hasCtelem4</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer/salus:Address</Tablename>
            <Projections>
                <Attribute>/salus:ctelem4</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#mixedattr1</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer/salus:Address/salus:ctelem4</Tablename>
            <Projections>
                <Attribute>/@mixedattr1</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#mixedattr2</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer/salus:Address/salus:ctelem4</Tablename>
            <Projections>
                <Attribute>/@mixedattr2</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#elemSimpleAndComplex</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer/salus:Address</Tablename>
            <Projections>
                <Attribute>/salus:elemSimpleAndComplex</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.salusproject.eu/ontology/test#elemSimpleAndComplex</Ontology>
        <Mapping connectionName="C:\Users\Rizkallah\Documents\tpc_di\test_instance.xml" sourceKind="xml">
            <Tablename>/salus:customer</Tablename>
            <Projections>
                <Attribute>/salus:elemSimpleAndComplex</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
</OntologyMappings>
