<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE OntologyMappings [<!ELEMENT OntologyMappings (Connections?, OntologyMapping+)>
<!ELEMENT Connections (Connection*)>
<!ELEMENT Connection (name, server, type, access+, database, port, username, password)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT server (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT access (#PCDATA)>
<!ELEMENT database (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT OntologyMapping (Ontology,RefOntology?,Mapping)>
<!ELEMENT SQLOperator (#PCDATA)>
<!ELEMENT Ontology (#PCDATA)>
<!ELEMENT RefOntology (#PCDATA)>
<!ELEMENT Mapping (((Mapping,SQLOperator)*,Mapping)|(Tablename,Projections,Selections?))>
<!ELEMENT Tablename (#PCDATA)>
<!ELEMENT Projections (Attribute+)>
<!ELEMENT Attribute (#PCDATA)>
<!ELEMENT Selections (Selection+)>
<!ELEMENT Selection (Column,Operator,Constant)>
<!ELEMENT Column (#PCDATA)>
<!ELEMENT Operator (#PCDATA)>
<!ELEMENT Constant (#PCDATA)>
<!ATTLIST Mapping connectionName CDATA #IMPLIED>
<!ATTLIST Mapping sourceKind CDATA #IMPLIED>
<!ATTLIST Ontology type (concept|property) #REQUIRED>
<!ATTLIST RefOntology type (concept|property) #REQUIRED>
]>

<OntologyMappings>
    <Connections>
        <Connection>
            <name>tpcdi</name>
            <server>localhost</server>
            <type>MySQL</type>
            <access/>
            <database>tpcdi</database>
            <port/>
            <username>sqluser</username>
            <password>sqluserpw</password>
        </Connection>
    </Connections>
    <OntologyMapping>
        <Ontology type="concept">http://www.upc.edu/it4bi/rt/tpcdi#account</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#cdc_flag</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>cdc_flag</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#cdc_dsn</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>cdc_dsn</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ca_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ca_b_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_b_id</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ca_c_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_c_id</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ca_name</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_name</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ca_tax_st</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_tax_st</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ca_st_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_st_id</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ACCOUNT_CUSTOMER_FK</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ACCOUNT_STATUS_TYPE_FK</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_st_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.upc.edu/it4bi/rt/tpcdi#cash_transaction</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>cash_transaction</Tablename>
            <Projections>
                <Attribute>ct_ca_id</Attribute>
                <Attribute>ct_dts</Attribute>
                <Attribute>ct_amt</Attribute>
                <Attribute>ct_name</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ct_ca_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>cash_transaction</Tablename>
            <Projections>
                <Attribute>ct_ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ct_dts</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>cash_transaction</Tablename>
            <Projections>
                <Attribute>ct_dts</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ct_amt</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>cash_transaction</Tablename>
            <Projections>
                <Attribute>ct_amt</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ct_name</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>cash_transaction</Tablename>
            <Projections>
                <Attribute>ct_name</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#CASH_TRANSACTION_ACCOUNT_FK</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>cash_transaction</Tablename>
            <Projections>
                <Attribute>ct_ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.upc.edu/it4bi/rt/tpcdi#customer</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#cdc_flag</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>cdc_flag</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#cdc_dsn</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>cdc_dsn</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_tax_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_tax_id</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_st_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_st_id</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_l_name</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_l_name</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_f_name</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_f_name</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_m_name</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_m_name</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_gndr</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_gndr</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_tier</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_tier</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_dob</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_dob</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_adline1</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_adline1</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_adline2</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_adline2</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_zipcode</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_zipcode</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_city</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_city</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_state_prov</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_state_prov</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_ctry</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_ctry</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_ctry_1</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_ctry_1</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_area_1</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_area_1</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_local_1</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_local_1</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_ext_1</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_ext_1</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_ctry_2</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_ctry_2</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_area_2</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_area_2</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_local_2</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_local_2</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_ext_2</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_ext_2</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_ctry_3</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_ctry_3</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_area_3</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_area_3</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_local_3</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_local_3</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_ext_3</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_ext_3</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_email_1</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_email_1</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_email_2</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_email_2</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_lcl_tx_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_lcl_tx_id</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#c_nat_tx_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_nat_tx_id</Attribute>
                <Attribute>c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#CUSTOMER_TAX_RATE_FK</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>customer</Tablename>
            <Projections>
                <Attribute>c_nat_tx_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.upc.edu/it4bi/rt/tpcdi#date</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#sk_dateid</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#datevalue</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>datevalue</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#datedesc</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>datedesc</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#calendaryearid</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>calendaryearid</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#calendaryeardesc</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>calendaryeardesc</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#calendarqtrid</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>calendarqtrid</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#calendarqtrdesc</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>calendarqtrdesc</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#calendarmonthid</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>calendarmonthid</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#calendarmonthdesc</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>calendarmonthdesc</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#calendarweekid</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>calendarweekid</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#calendarweekdesc</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>calendarweekdesc</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#dayofweeknum</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>dayofweeknum</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#dayofweekdesc</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>dayofweekdesc</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#fiscalyearid</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>fiscalyearid</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#fiscalyeardesc</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>fiscalyeardesc</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#fiscalqtrid</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>date</Tablename>
            <Projections>
                <Attribute>fiscalqtrid</Attribute>
                <Attribute>sk_dateid</Attribute>
            </Projections>
        </Mapping>