<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE OntologyMappings [<!ELEMENT OntologyMappings (Connections?, OntologyMapping+)>
<!ELEMENT Connections (Connection*)>
<!ELEMENT Connection (name, server, type, access+, database, port, username, password)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT server (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT access (#PCDATA)>
<!ELEMENT database (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT OntologyMapping (Ontology,RefOntology?,Mapping)>
<!ELEMENT SQLOperator (#PCDATA)>
<!ELEMENT Ontology (#PCDATA)>
<!ELEMENT RefOntology (#PCDATA)>
<!ELEMENT Mapping (((Mapping,SQLOperator)*,Mapping)|(Tablename,Projections,Selections?))>
<!ELEMENT Tablename (#PCDATA)>
<!ELEMENT Projections (Attribute+)>
<!ELEMENT Attribute (#PCDATA)>
<!ELEMENT Selections (Selection+)>
<!ELEMENT Selection (Column,Operator,Constant)>
<!ELEMENT Column (#PCDATA)>
<!ELEMENT Operator (#PCDATA)>
<!ELEMENT Constant (#PCDATA)>
<!ATTLIST Mapping connectionName CDATA #IMPLIED>
<!ATTLIST Mapping sourceKind CDATA #IMPLIED>
<!ATTLIST Ontology type (concept|property) #REQUIRED>
<!ATTLIST RefOntology type (concept|property) #REQUIRED>
]>

<OntologyMappings>
    <Connections>
        <Connection>
            <name>tpcdi</name>
            <server>localhost</server>
            <type>MySQL</type>
            <access/>
            <database>tpcdi</database>
            <port/>
            <username>sqluser</username>
            <password>sqluserpw</password>
        </Connection>
    </Connections>
    <OntologyMapping>
        <Ontology type="concept">http://www.tpc.org/tpc-di#Actions</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename/>
            <Projections>
                <Attribute>/TPCDI:Actions</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.tpc.org/tpc-di#ActionDef</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions</Tablename>
            <Projections>
                <Attribute>/TPCDI:Action/node()</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#hasAction</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions</Tablename>
            <Projections>
                <Attribute>/TPCDI:Action</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#ActionTS</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action</Tablename>
            <Projections>
                <Attribute>/@ActionTS</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#ActionType</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action</Tablename>
            <Projections>
                <Attribute>/@ActionType</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.tpc.org/tpc-di#Customer</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action</Tablename>
            <Projections>
                <Attribute>/Customer/node()</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#hasCustomer</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action</Tablename>
            <Projections>
                <Attribute>/Customer</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_DOB</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/@C_DOB</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_GNDR</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/@C_GNDR</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_ID</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/@C_ID</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_TAX_ID</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/@C_TAX_ID</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_TIER</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/@C_TIER</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.tpc.org/tpc-di#Name</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/Name/node()</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#hasName</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/Name</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_L_NAME</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/Name</Tablename>
            <Projections>
                <Attribute>/C_L_NAME</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_F_NAME</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/Name</Tablename>
            <Projections>
                <Attribute>/C_F_NAME</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_M_NAME</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/Name</Tablename>
            <Projections>
                <Attribute>/C_M_NAME</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.tpc.org/tpc-di#Address</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/Address/node()</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#hasAddress</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/Address</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_ADLINE1</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/Address</Tablename>
            <Projections>
                <Attribute>/C_ADLINE1</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_ADLINE2</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/Address</Tablename>
            <Projections>
                <Attribute>/C_ADLINE2</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_ZIPCODE</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/Address</Tablename>
            <Projections>
                <Attribute>/C_ZIPCODE</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_CITY</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/Address</Tablename>
            <Projections>
                <Attribute>/C_CITY</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_STATE_PROV</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/Address</Tablename>
            <Projections>
                <Attribute>/C_STATE_PROV</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_CTRY</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/Address</Tablename>
            <Projections>
                <Attribute>/C_CTRY</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.tpc.org/tpc-di#ContactInfo</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/ContactInfo/node()</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#hasContactInfo</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/ContactInfo</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_PRIM_EMAIL</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo</Tablename>
            <Projections>
                <Attribute>/C_PRIM_EMAIL</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.tpc.org/tpc-di#PhoneNumber</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo</Tablename>
            <Projections>
                <Attribute>/C_PHONE_1/node()</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#hasC_PHONE_1</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo</Tablename>
            <Projections>
                <Attribute>/C_PHONE_1</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_AREA_CODE</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo/C_PHONE_1</Tablename>
            <Projections>
                <Attribute>/C_AREA_CODE</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_LOCAL</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo/C_PHONE_1</Tablename>
            <Projections>
                <Attribute>/C_LOCAL</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_EXT</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo/C_PHONE_1</Tablename>
            <Projections>
                <Attribute>/C_EXT</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.tpc.org/tpc-di#PhoneNumber</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo</Tablename>
            <Projections>
                <Attribute>/C_PHONE_2/node()</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#hasC_PHONE_2</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo</Tablename>
            <Projections>
                <Attribute>/C_PHONE_2</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_LOCAL</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo/C_PHONE_2</Tablename>
            <Projections>
                <Attribute>/C_LOCAL</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.tpc.org/tpc-di#PhoneNumber</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo</Tablename>
            <Projections>
                <Attribute>/C_PHONE_3/node()</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#hasC_PHONE_3</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo</Tablename>
            <Projections>
                <Attribute>/C_PHONE_3</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.tpc.org/tpc-di#TaxInfo</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/TaxInfo/node()</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#hasTaxInfo</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/TaxInfo</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_LCL_TX_ID</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/TaxInfo</Tablename>
            <Projections>
                <Attribute>/C_LCL_TX_ID</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_NAT_TX_ID</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/TaxInfo</Tablename>
            <Projections>
                <Attribute>/C_NAT_TX_ID</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.tpc.org/tpc-di#Account</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/Account/node()</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#hasAccount</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer</Tablename>
            <Projections>
                <Attribute>/Account</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#CA_ID</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/Account</Tablename>
            <Projections>
                <Attribute>/@CA_ID</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#CA_TAX_ST</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/Account</Tablename>
            <Projections>
                <Attribute>/@CA_TAX_ST</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#CA_B_ID</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/Account</Tablename>
            <Projections>
                <Attribute>/CA_B_ID</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#CA_NAME</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/Account</Tablename>
            <Projections>
                <Attribute>/CA_NAME</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_CTRY_CODE</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo/C_PHONE_2</Tablename>
            <Projections>
                <Attribute>/C_CTRY_CODE</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_AREA_CODE</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo/C_PHONE_2</Tablename>
            <Projections>
                <Attribute>/C_AREA_CODE</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_CTRY_CODE</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo/C_PHONE_1</Tablename>
            <Projections>
                <Attribute>/C_CTRY_CODE</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.tpc.org/tpc-di#C_ALT_EMAIL</Ontology>
        <Mapping connectionName="test\tpc_di\cust_mgmt_instance_extract.xml" sourceKind="xml">
            <Tablename>/TPCDI:Actions/TPCDI:Action/Customer/ContactInfo</Tablename>
            <Projections>
                <Attribute>/C_ALT_EMAIL</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.upc.edu/it4bi/rt/tpcdi#account</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#cdc_flag</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>cdc_flag</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#cdc_dsn</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>cdc_dsn</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ca_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ca_b_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_b_id</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ca_c_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_c_id</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ca_name</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_name</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ca_tax_st</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_tax_st</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ca_st_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_st_id</Attribute>
                <Attribute>ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ACCOUNT_CUSTOMER_FK</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_c_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ACCOUNT_STATUS_TYPE_FK</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>account</Tablename>
            <Projections>
                <Attribute>ca_st_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="concept">http://www.upc.edu/it4bi/rt/tpcdi#cash_transaction</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>cash_transaction</Tablename>
            <Projections>
                <Attribute>ct_ca_id</Attribute>
                <Attribute>ct_dts</Attribute>
                <Attribute>ct_amt</Attribute>
                <Attribute>ct_name</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ct_ca_id</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>cash_transaction</Tablename>
            <Projections>
                <Attribute>ct_ca_id</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ct_dts</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>cash_transaction</Tablename>
            <Projections>
                <Attribute>ct_dts</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>
        <Ontology type="property">http://www.upc.edu/it4bi/rt/tpcdi#ct_amt</Ontology>
        <Mapping connectionName="tpcdi" sourceKind="relational">
            <Tablename>cash_transaction</Tablename>
            <Projections>
                <Attribute>ct_amt</Attribute>
            </Projections>
        </Mapping>
    </OntologyMapping>
    <OntologyMapping>